# Generated by Django 5.1 on 2024-12-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='iteml',
            new_name='items',
        ),
    ]
