# Generated by Django 5.1 on 2024-12-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_iteml_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='file',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
