# Generated by Django 5.1 on 2025-01-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('total_amt', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=40)),
            ],
        ),
    ]
