# Generated by Django 5.1 on 2025-01-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='session_key',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
