# Generated by Django 5.1 on 2025-01-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_item_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='session_key',
            field=models.CharField(max_length=50),
        ),
    ]
